[project]
name = "graphiti-mcp-server-claude-docker"
version = "0.1.0"
description = "Graphiti MCP Server with Claude Docker support"
dependencies = [
    "mcp>=0.9.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"