# Docker Compose file for Islamic Text Workflow development environment

services:
  # Main development environment
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: development
    volumes:
      - ..:/workspace:cached
      - python_packages:/home/developer/.local
      - vscode_extensions:/home/developer/.vscode-server
      - graphiti_data:/workspace/graphiti-data
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace:/workspace/graphiti-main
      - ISLAMIC_TEXT_WORKFLOW=/workspace
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - GRAPHITI_DATA_DIR=/workspace/graphiti-data
    networks:
      - islamic-dev-network
    depends_on:
      neo4j:
        condition: service_healthy
    # Note: Removed claude-docker-api dependency - using existing instance
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  # Note: Using existing claude-docker-api container running on port 8000

  # Neo4j Database for Graphiti Knowledge Graph
  neo4j:
    image: neo4j:5.15
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1024m
    ports:
      - "7474:7474"  # Browser interface
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - islamic-dev-network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Optional: Documentation server (disabled for minimal setup)
  # docs:
  #   image: nginx:alpine
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ../documentation:/usr/share/nginx/html/docs:ro
  #     - ../README.md:/usr/share/nginx/html/index.md:ro
  #   networks:
  #     - islamic-dev-network

volumes:
  python_packages:
    driver: local
  vscode_extensions:
    driver: local
  graphiti_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

networks:
  islamic-dev-network:
    driver: bridge