# Docker Compose file for Islamic Text Workflow development environment

services:
  # Main development environment
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: development
    volumes:
      - ..:/workspace:cached
      - python_packages:/home/developer/.local
      - vscode_extensions:/home/developer/.vscode-server
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace:/workspace/graphiti-main
      - ISLAMIC_TEXT_WORKFLOW=/workspace
    networks:
      - islamic-dev-network
    # Note: Removed claude-docker-api dependency - using existing instance
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  # Note: Using existing claude-docker-api container running on port 8000

  # Optional: Documentation server (disabled for minimal setup)
  # docs:
  #   image: nginx:alpine
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ../documentation:/usr/share/nginx/html/docs:ro
  #     - ../README.md:/usr/share/nginx/html/index.md:ro
  #   networks:
  #     - islamic-dev-network

volumes:
  python_packages:
    driver: local
  vscode_extensions:
    driver: local

networks:
  islamic-dev-network:
    driver: bridge