# Graphiti Configuration for NLP Pipeline Mode
# This configuration is optimized for text processing pipelines

mode: nlp_pipeline

# Neo4j database configuration
neo4j:
  uri: bolt://neo4j:7687  # Using Docker network name
  user: neo4j
  password: password
  database: neo4j

# LLM configuration
llm:
  provider: anthropic  # Use API bridge for worker coordination
  model: claude-3-sonnet-20240229
  api_key: local
  base_url: http://localhost:8000  # Claude Docker API bridge
  
# Embedder configuration  
embedder:
  provider: gemini
  model: models/text-embedding-004
  api_key: ${GOOGLE_API_KEY}

# Dynamic entity types - can be overridden per request
entity_types:
  Entity:
    description: "Generic entity type"
    fields:
      - name: string
      - type: string
      - attributes: dict
      
  Person:
    description: "A person mentioned in text"
    fields:
      - name: string
      - role: string
      - organization: string
      
  Organization:
    description: "An organization or company"
    fields:
      - name: string
      - type: string
      - location: string
      
  Location:
    description: "A geographical location"
    fields:
      - name: string
      - type: string
      - coordinates: dict
      
  Event:
    description: "An event or occurrence"
    fields:
      - name: string
      - date: string
      - participants: list[string]
      
  Concept:
    description: "An abstract concept or idea"
    fields:
      - name: string
      - domain: string
      - definition: string
      
  Document:
    description: "A document or text source"
    fields:
      - title: string
      - author: string
      - date: string
      - type: string

# Edge types for text relationships
edge_types:
  MENTIONS:
    description: "Document mentions entity"
    source_types: [Document]
    target_types: [Entity, Person, Organization, Location, Event, Concept]
    
  RELATES_TO:
    description: "Generic relationship between entities"
    source_types: [Entity]
    target_types: [Entity]
    
  WORKS_FOR:
    description: "Person works for organization"
    source_types: [Person]
    target_types: [Organization]
    
  LOCATED_IN:
    description: "Entity is located in location"
    source_types: [Entity, Organization, Event]
    target_types: [Location]
    
  PARTICIPATES_IN:
    description: "Person participates in event"
    source_types: [Person]
    target_types: [Event]
    
  AUTHORED_BY:
    description: "Document authored by person"
    source_types: [Document]
    target_types: [Person]
    
  REFERENCES:
    description: "Document references another document"
    source_types: [Document]
    target_types: [Document]

# Worker communication settings
worker:
  # Input/output format
  message_format: json
  
  # Batch processing settings
  batch_size: 10
  max_batch_wait: 5  # seconds
  
  # Error handling
  retry_attempts: 3
  retry_delay: 1  # seconds
  
  # Queue settings (if using message queue)
  input_queue: graphiti_input
  output_queue: graphiti_output
  
  # Coordination
  coordination_timeout: 300  # seconds
  heartbeat_interval: 30  # seconds

# Processing settings
processing:
  # Accept dynamic entity types from upstream workers
  accept_dynamic_types: true
  
  # Merge entities across batches
  enable_entity_merging: true
  
  # Track document sources
  track_provenance: true
  
  # Enable incremental updates
  incremental_mode: true

# Search configuration
search:
  # Optimized for text retrieval
  default_type: NODE_HYBRID_SEARCH_RRF
  
  # Return more results for downstream processing
  default_num_results: 50
  
  # Include source documents
  include_sources: true

# Integration settings
integration:
  # Support for streaming results
  enable_streaming: true
  
  # Checkpoint support for long-running processes
  enable_checkpoints: true
  checkpoint_interval: 100  # episodes
  
  # Shared graph access
  allow_concurrent_access: true
  lock_timeout: 30  # seconds

# Prompts for text analysis
prompts:
  entity_extraction: |
    Extract entities from the following text.
    Identify people, organizations, locations, events, and key concepts.
    Preserve the original text context for each entity.
    
  relationship_analysis: |
    Identify relationships between entities in this text.
    Look for explicit and implicit connections.
    Consider temporal and causal relationships.
    
  document_summary: |
    Provide a concise summary of this document.
    Focus on key entities and their relationships.