-- Enrichment for: Ahl al-Bayt al-Qiyadah al-Rabbaniyyah by Sayyed Kazem Mohammad Jawad
-- UUID: ff772a96-9977-43ef-a789-62aca6b855ec
-- Agent: agent-metadata-expert-002 (Metadata Enrichment Expert)
-- Generated: 2025-07-04

UPDATE books SET 
  title_alias = 'Ahl al-Bayt the Divine Leadership; The Prophet''s Family Divine Authority; Ahl al-Bayt al-Qiyadah al-Rabbaniyyah; Divine Leadership of Ahl al-Bayt; The Prophets Family Divine Government; Ahl al-Bayt Rabbaniyyah Leadership; Divine Authority of the Household; The Sacred Leadership; Qiyadah Rabbaniyyah; Lordly Leadership of Ahl al-Bayt; Divine Governance through Prophets Family; Ahl al-Bayt Sacred Authority',
  keywords = ARRAY[
    'Ahl al-Bayt', 'Prophets family', 'Divine leadership', 'Qiyadah Rabbaniyyah', 'Rabbaniyyah', 'Lordly authority', 'Divine authority', 'Sacred leadership', 'Imamate', 'Imamah', 'Wilayah', 'Guardianship', 'Divine appointment', 'Nass', 'Designation', 'Infallibility', 'Ismah', 'Divine knowledge', 'Ilm Ladunni', 'Spiritual authority', 'Wilayat Takwiniyyah', 'Political theology', 'Islamic governance', 'Divine government', 'Khalifat Allah', 'Divine vicegerency', 'Uli al-Amr', 'Those in authority', 'Hadith al-Ghadir', 'Ghadir Khumm', 'Hadith al-Thaqalayn', 'Two weighty things', 'Hadith al-Kisa', 'Tradition of the Cloak', 'Ayat al-Tathir', 'Verse of Purification', 'Ayat Uli al-Amr', 'Verse of Authority', 'Twelve Imams', 'Ithna Ashar', 'Ali ibn Abi Talib', 'Fatimah', 'Hasan', 'Husayn', 'Purified ones', 'Masumin', 'Fourteen Infallibles', 'Prophetic succession', 'Legitimate authority', 'Divine mandate', 'Theological argumentation', 'Kalam', 'Quranic exegesis', 'Tafsir', 'Political theory', 'Islamic political thought', 'Shia political theology', 'Religious authority', 'Marjaiyyah', 'Wilayat al-Faqih', 'Guardianship of Jurist', 'Marja', 'Source of emulation', 'Taqiyyah', 'Precautionary dissimulation', 'Intizar', 'Awaiting', 'Mahdi', 'Imam al-Mahdi', 'Eschatology', 'End times', 'Divine justice', 'Global governance', 'Intercession', 'Shafaah', 'Miracles', 'Karamat', 'Divine favor', 'Obedience', 'Taat', 'Love', 'Mahabbah', 'Devotion', 'Tawalli', 'Following', 'Ittiba', 'Dissociation', 'Tabarra', 'Religious obligations', 'Takalif Diniyyah', 'Spiritual purification', 'Divine guidance', 'Authentic Islam', 'Religious legitimacy', 'Sacred authority', 'Heavenly mandate'
  ],
  description = 'A comprehensive theological treatise examining the divine leadership authority of the Prophet''s household (Ahl al-Bayt), authored by Sayyed Kazem Mohammad Jawad. The work systematically demonstrates that legitimate Islamic leadership belongs exclusively to the Ahl al-Bayt through divine mandate, combining Quranic exegesis, hadith analysis, and theological argumentation. The book explores the foundational concepts of divine leadership (Qiyadah Rabbaniyyah), infallibility (Ismah) as prerequisite for governance, and the extension of Prophethood through the Imamate. Key themes include the analysis of Quranic verses supporting divine appointment, the concept of Wilayah (guardianship) and its political implications, and the distinction between divinely appointed and humanly elected leadership. The study encompasses the theological necessity of infallible leaders, the role of divine knowledge in governance, and the historical implementation of divine leadership principles. The work serves as a significant contribution to Islamic political theology, establishing the doctrinal foundation for understanding the Ahl al-Bayt as holders of ultimate religious and temporal authority in Islamic governance.'
WHERE id = 'ff772a96-9977-43ef-a789-62aca6b855ec';