-- Enrichment SQL for Ahl al-Bayt by al-Muhaqqiq al-Tabataba'i
-- Book ID: 1ebdd49d-a229-4064-ab0c-55bf603eccf1
-- Generated by Islamic-Text-Processor-5 following ENRICHMENT_CRITERIA.md

UPDATE books 
SET 
    title_alias = 'The Family of the Prophet; Ahl al Bayt; Ahl-ul-Bayt; People of the House; The Household; Family of Muhammad; Aal al-Bayt; Al al-Bayt; The Prophet''s Family; The Sacred Household; Ahle Bait; The Purified Family',
    
    keywords = ARRAY[
        'Ahl al-Bayt', 'Prophet Muhammad family', 'Ali ibn Abi Talib', 'Fatima al-Zahra', 
        'Imam Hasan', 'Imam Husayn', 'Twelve Imams', 'Purification verse', 'Ayat al-Tathir',
        'Hadith al-Thaqalayn', 'Hadith al-Kisa', 'Two Weighty Things', 'Cloak tradition',
        'Wilayah', 'Guardianship', 'Ismah', 'Infallibility', 'Divine appointment',
        'Imamate', 'Succession', 'Spiritual authority', 'Bayt al-Nubuwwah',
        'House of Prophethood', 'Mawaddah verse', 'Love of family', 'Quran 33:33',
        'Quran 42:23', 'Shia theology', 'Shia Islam', 'Imami doctrine',
        'Sayyid Abd al-Aziz Tabataba''i', 'Muhaqqiq Tabataba''i', 'Tabataba''i family',
        'Manuscript studies', 'Codicology', 'Ilm al-rijal', 'Hadith science',
        'Islamic leadership', 'Prophetic tradition', 'Scriptural authority',
        'Theological treatise', 'Quranic exegesis', 'Tafsir', 'Islamic theology',
        'Kalam', 'Comparative religion', 'Sunni-Shia dialogue'
    ],
    
    description = 'A comprehensive theological-exegetical treatise by the renowned scholar Sayyid Abd al-Aziz Tabataba''i (al-Muhaqqiq al-Tabataba''i), systematically establishing the divine appointment, spiritual authority (Wilayah), and infallibility (Ismah) of Ahl al-Bayt through rigorous analysis of Quranic verses and authenticated Prophetic traditions. The work combines traditional Shi''a scholarship with modern manuscript studies and codicological expertise, providing definitive scriptural evidence for the special status of the Prophet''s family as divinely ordained guides for the Muslim community. Essential reading for understanding Imami theology and the foundations of Islamic leadership after the Prophet Muhammad.'

WHERE id = '1ebdd49d-a229-4064-ab0c-55bf603eccf1';