-- SQL Enrichment for: Ahsan al-Wadiah
-- UUID: aca6ad4e-fdde-4dd1-a4e6-c117ae4863fc
-- Author: Muhammad Mahdi Isfahan al-Kazimi
-- Generated by: Islamic-Text-Processor-10
-- Date: 2025-07-04

UPDATE books 
SET 
    title_alias = 'Ahsan al-Wadiah; The Best Deposit; The Most Excellent Trust; Ahsan al-Wadi_ah; The Best Compilation; The Excellent Deposit; The Most Reliable Trust; Ahsan al Wadiah; The Best Reference; The Excellent Compilation; The Trustworthy Deposit; The Most Excellent Reference; The Best Legal Compilation; The Excellent Jurisprudential Trust; The Most Reliable Legal Reference; The Best Fiqh Manual; The Excellent Jurisprudential Guide; The Trustworthy Legal Compendium; The Most Excellent Practical Manual; The Best Shia Legal Reference',
    
    keywords = '{"Shia Jurisprudence", "Jaafari Fiqh", "Islamic Law", "Usul al-Fiqh", "Ahl al-Bayt", "Twelver Shia", "Mujtahid", "Marja", "Ijtihad", "Taqlid", "Risalah Amaliyyah", "Tahara", "Ritual Purification", "Salat", "Prayer", "Siyam", "Fasting", "Zakat", "Khums", "Hajj", "Pilgrimage", "Muamalat", "Commercial Law", "Nikah", "Marriage", "Divorce", "Talaq", "Inheritance", "Faraid", "Hudud", "Criminal Law", "Tazir", "Qada", "Kaffarah", "Wudu", "Ablution", "Ghusl", "Tayammum", "Najasa", "Ritual Impurity", "Qiblah", "Jumu_ah", "Congregational Prayer", "Imam", "Prayer Leader", "Ramadan", "Zakat al-Fitr", "Umrah", "Ziyarat", "Bay", "Sale Contract", "Riba", "Usury", "Ijarah", "Lease", "Sharikah", "Partnership", "Rahn", "Mortgage", "Qasam", "Oath", "Shahadah", "Testimony", "Nikah Mut_ah", "Temporary Marriage", "Riddah", "Apostasy", "Sariqah", "Theft", "Zina", "Adultery", "Muhammad Mahdi Isfahan al-Kazimi", "Isfahan", "Kazimi", "Shia Scholar", "Legal Manual", "Practical Guide", "Contemporary Fiqh", "Traditional Jurisprudence", "Legal Reference", "Jurisprudential Compendium", "Islamic Legal Theory", "Shia Legal Tradition", "Fiqh Manual", "Legal Practice", "Religious Law", "Islamic Jurisprudence", "Legal Guidance", "Practical Jurisprudence", "Shia Legal Authority", "Legal Compilation", "Jurisprudential Reference", "Islamic Legal Practice", "Shia Legal Methodology", "Legal Rulings", "Jurisprudential Guidance", "Islamic Legal Manual", "Shia Legal System", "Legal Framework", "Jurisprudential Framework", "Islamic Legal Principles", "Shia Legal Principles", "Legal Theory", "Jurisprudential Theory", "Islamic Legal Literature", "Shia Legal Literature", "Legal Scholarship", "Jurisprudential Scholarship", "Islamic Legal Studies", "Shia Legal Studies", "Legal Education", "Jurisprudential Education"}',
    
    description = 'Ahsan al-Wadiah (The Best Deposit) is a comprehensive jurisprudential compendium by Muhammad Mahdi Isfahan al-Kazimi that systematically presents Shia Jaafari legal rulings across all domains of Islamic practice. This work serves as both a reference manual and practical guide, methodically covering Islamic law from ritual purification (tahara) to commercial transactions (muamalat), marriage law (nikah), and criminal law (hudud). Based on classical Shia usul al-fiqh methodology integrating Kitab, Sunnah, and ijma al-A_immah with rational derivation, the work emphasizes adherence to Ahl al-Bayt legal tradition while addressing contemporary practical needs. As a typical example of modern Shia legal scholarship, it functions as a trustworthy deposit (wadiah) of the most excellently compiled (ahsan) legal rulings for contemporary Shia practitioners, balancing traditional authority with practical application in the modern context.'

WHERE id = 'aca6ad4e-fdde-4dd1-a4e6-c117ae4863fc';

-- Verification query
SELECT id, title, title_alias, keywords, description, updated_at 
FROM books 
WHERE id = 'aca6ad4e-fdde-4dd1-a4e6-c117ae4863fc';