-- Islamic Text Processor 3 - Book Enrichment
-- Book: al-Bahr al-Zakhar
-- Author: al-Sayyid Muhsin al-Amin
-- Processing Date: 2025-07-04

UPDATE books 
SET 
    title_alias = 'Al-Bahr al-Zakhar; The Abundant Sea; The Flowing Ocean; Al Bahr al Zakhar; Biographical Encyclopedia; Shia Scholars Encyclopedia; Lives of Shia Scholars; Biographical Dictionary; al-Amin Biographical Work; Scholars of Shia Islam; Intellectual Heritage; Biographical Compilation; Shia Prosopography; Scholarly Biographies',
    
    keywords = ARRAY[
        'al-Sayyid Muhsin al-Amin', 'Biographical encyclopedia', 'Shia scholars', 'Intellectual traditions', 'Lebanese scholarship', 'Jabal Amil', 'Scholarly heritage', 'Prosopography', 'Rijal studies', 'Biographical evaluation', 'Intellectual genealogies', 'Asanid al-Ilm', 'Scholarly transmission', 'Tabaqat', 'Biographical compilation', 'Shia intellectual history', 'Islamic biography', 'Scholarly documentation', 'Heritage preservation', 'Intellectual continuity', 'Scholarly legitimacy', 'Institutional memory', 'Shia identity', 'Lebanese Shia renaissance', 'Modernization of scholarship', 'Traditional scholarship', 'Contemporary methods', 'Ashab al-Aimmah', 'Companions of Imams', 'Zurara ibn Ayun', 'Muhammad ibn Muslim', 'Four Books authors', 'Kutub al-Arbaah', 'al-Kulayni', 'al-Saduq', 'al-Tusi', 'al-Mufid', 'Early jurists', 'Fuqaha al-Qudama', 'Usul al-Fiqh', 'Ijtihad', 'Silsilat al-Ijaza', 'Baghdad School', 'Shaykh al-Mufid', 'al-Sharif al-Murtada', 'Shaykh al-Tusi', 'Ashari theologians', 'Mutazili theologians', 'Najaf scholarly center', 'Hillah School', 'Allamah al-Hilli', 'Banu Hilli', 'Aristotelian philosophy', 'Shia theology', 'Regional scholarly centers', 'Jabal Amil scholars', 'Safavid scholarship', 'Lebanese scholarly families', 'Renewal movement', 'Harakat al-Tajdid', 'Muhammad Abduh', 'Modern Ijtihad', 'Institutional development', 'Najaf Seminary', 'Maraji al-Taqlid', 'Hawza education', 'Contemporary scholars', 'Intellectual renaissance', 'Academic methods', 'Muhaddithun', 'Hadith scholars', 'Ilm al-Rijal', 'Authentication', 'Mufassirun', 'Exegetes', 'Commentators', 'Interpretive methodologies', 'Mutakallimun', 'Theologians', 'Systematic theology', 'Doctrinal contributions', 'Fuqaha', 'Jurists', 'Legal scholars', 'Jurisprudential innovations', 'Geographical distribution', 'Chronological development', 'Scholarly institutions', 'Family dynasties', 'Intellectual contributions', 'Research methods', 'Oral traditions', 'Family archives', 'Critical evaluation', 'Source reliability', 'Scholarly genealogies', 'Intellectual transmission', 'Certification systems', 'Ijaza', 'Scholarly authenticity', 'Continuing tradition', 'Future of scholarship', 'Reference work', 'Communal identity', 'Scholarly research', 'Historical documentation', 'Academic standards', 'Islamic biographical literature', 'Intellectual legitimacy', 'Centuries of history', 'Scholarly continuity'
    ],
    
    description = 'A monumental biographical encyclopedia by al-Sayyid Muhsin al-Amin (1865-1952) documenting the lives, works, and intellectual contributions of Shia scholars throughout Islamic history. This comprehensive prosopographical work preserves the scholarly heritage and establishes the historical continuity of Shia intellectual traditions from the early companions of the Imams to contemporary scholars. Al-Amin systematically documents intellectual genealogies, scholarly transmission chains, and the development of major Shia scholarly centers including Baghdad, Najaf, and Jabal Amil. The work serves as both a reference tool for researchers and a foundational text for understanding Shia intellectual identity, covering early authorities, classical period masters, and modern scholars while employing rigorous biographical methodology combining traditional sources with contemporary academic standards. Essential for Islamic biographical studies and Shia intellectual history research.'

WHERE id = '76edf54a-b20d-408e-97ca-6282c85c29e4';