-- SQL Enrichment for Al-Dhunub al-Kabirah by Sayyid Abd al-Husayn Dastghayb Shirazi
-- UUID: 036e42ea-f2ed-49a2-8d2b-ddc6d8ae6eb6
-- Generated: 2025-07-04
-- Agent: agent-diagnostic-islamic-studies-001

UPDATE books 
SET 
    title_alias = 'Greater Sins; Al-Dhunub al-Kabirah; Al Dhunub al Kabirah; Gunahane Kabira; Greater Sins Volume 1; Greater Sins Volume 2; Greater Sins Volume 3; The Major Sins; Al-Kaba''ir; Al Kaba''ir; Kabira Sins; The Great Sins; Major Sins of Islam; Gunahan-i Kabira; Al-Dhunub al-Kabira; Greater Sins Book; Major Sins Manual; Islamic Ethics Guide; Sins Classification; The Fifty Major Sins; Ethical Treatise; Dastghayb Greater Sins; Shirazi Greater Sins; Al-Dhunub al-Kabirah Shirazi',
    
    keywords = ARRAY['major sins', 'kabair', 'greater sins', 'Islamic ethics', 'moral theology', 'Shia jurisprudence', 'fiqh', 'Sayyid Dastghayb', 'Dastghayb Shirazi', 'Ayatullah Dastghayb', 'shirk', 'polytheism', 'murder', 'qatl', 'adultery', 'zina', 'theft', 'sariqa', 'false accusation', 'qazf', 'intoxicants', 'khamr', 'alcohol prohibition', 'gambling', 'qimar', 'interest', 'riba', 'usury', 'disobedience to parents', 'uquq al-walidayn', 'cutting family ties', 'qat al-rahim', 'false witness', 'shahada zur', 'oppression', 'zulm', 'repentance', 'tawba', 'spiritual purification', 'nadam', 'itiraf', 'azm', 'divine mercy', 'rahma', 'forgiveness', 'Islamic law', 'Shia Islam', 'Imami jurisprudence', 'moral conduct', 'spiritual development', 'ethical guidance', 'sin classification', 'saghair', 'minor sins', 'eschatology', 'maad', 'afterlife', 'punishment', 'reward', 'Islamic morality', 'religious obligations', 'community ethics', 'social responsibility', 'individual conduct', 'spiritual salvation', 'religious education', 'Islamic teachings', 'prophetic traditions', 'hadith', 'Quranic exegesis', 'tafsir', 'Islamic philosophy', 'moral philosophy', 'behavioral ethics', 'practical ethics', 'religious law', 'Islamic civilization', 'Muslim scholars', 'contemporary Islam', 'traditional Islam', 'moral guidance', 'spiritual discipline', 'religious practice', 'Islamic lifestyle', 'moral purification', 'soul purification', 'divine law', 'sharia', 'Islamic culture', 'religious literature', 'Islamic studies', 'comparative religion', 'ethical theory', 'virtue ethics', 'Islamic virtues', 'religious conduct', 'piety', 'taqwa', 'God-consciousness', 'Islamic spirituality', 'mysticism', 'akhlaq', 'character development', 'moral improvement', 'self-reformation', 'Islamic education', 'religious instruction', 'spiritual guidance', 'Islamic scholarship', 'jurisprudential manual', 'ethical treatise', 'religious text', 'Islamic book', 'educational resource', 'moral reference', 'spiritual manual', 'religious guidance', 'Islamic wisdom', 'moral teachings', 'spiritual lessons', 'ethical principles', 'religious principles', 'Islamic doctrine', 'theological ethics', 'religious ethics', 'divine commandments', 'prophetic guidance', 'Islamic tradition', 'religious tradition', 'spiritual tradition', 'moral tradition', 'ethical tradition', 'Islamic heritage', 'religious heritage', 'spiritual heritage', 'moral heritage', 'ethical heritage'],
    
    description = 'A comprehensive multi-volume ethical treatise and jurisprudential manual by Ayatullah Sayyid Abd al-Husayn Dastghayb Shirazi (1913-1981), systematically examining the fifty major sins (al-kaba''ir) in Islamic jurisprudence according to Shia Imami tradition. This foundational work combines Quranic exegesis, prophetic traditions, and jurisprudential analysis to provide both theoretical understanding and practical guidance for avoiding major transgressions. The author, a prominent Shia jurist and Friday prayer leader in Shiraz who was martyred in 1981, presents detailed analysis of sins ranging from shirk (polytheism) and murder to economic transgressions like riba (usury) and social violations like disobedience to parents. Each volume addresses specific categories of major sins while providing comprehensive coverage of repentance (tawba), spiritual purification, and the path to divine forgiveness. The work distinguishes between major sins (kaba''ir) and minor sins (sagha''ir), offering practical guidelines for maintaining Islamic moral conduct in both individual and communal contexts. With over a million copies sold, this influential text serves as both a scholarly reference and a practical guide for spiritual development, making traditional Islamic ethical teachings accessible to contemporary readers while maintaining rigorous jurisprudential standards. The systematic approach integrates legal, spiritual, and social dimensions of Islamic ethics, providing essential guidance for understanding the consequences of moral transgressions and the mechanisms for spiritual redemption in Islamic theology.'

WHERE id = '036e42ea-f2ed-49a2-8d2b-ddc6d8ae6eb6';