-- ======================================================================
-- BOOK 1: Al-Infq Fi Sabil Allah
-- Author: Az Al-Din Bahr Al-Ulum
-- Processed: 2025-07-03
-- Status: PENDING
-- ======================================================================

UPDATE books SET
  title_alias = 'Spending in the Way of Allah; Al-Infaq Fi Sabil Allah; Al Infq Fi Sabil Allah; Al-Infaq Fi Sabeel Allah; Spending in Allah''s Path; Charitable Giving in Islam; Al Infaq Fi Sabeel Allah; El-Infaq Fi Sabil Allah; Islamic Charity and Giving; The Way of Allah Spending',
  keywords = '{"Infq", "Infaq", "Spending in the way of Allah", "Charitable giving", "Islamic charity", "Sabil Allah", "Path of Allah", "Zakat", "Sadaqah", "Qard Hasan", "Az Al-Din Bahr Al-Ulum", "Bahr al-Ulum", "Ocean of Knowledge", "Tazkiyah", "Purification", "Wealth distribution", "Islamic economics", "Taqwa", "God-consciousness", "Spiritual purification", "Social justice", "Voluntary charity", "Mandatory charity", "Khums", "Nafaqah", "Jurisprudence", "Fiqh", "Usul al-Fiqh", "Shia Imami", "Theology", "Kalam", "Quranic exegesis", "Hadith studies", "Mystical spirituality", "Divine proximity", "Qurb", "Ahl al-Bayt", "Religious obligation", "Economic ethics", "Ikhlas", "Sincerity", "Riya", "Ostentation"}',
  description = 'In "Al-Infq Fi Sabil Allah," Az Al-Din Bahr Al-Ulum analyzes the comprehensive Islamic doctrine of charitable giving through systematic jurisprudential methodology. Bahr Al-Ulum establishes that *Infq Fi Sabil Allah* represents the highest form of charitable giving that encompasses all spending aimed at seeking Allah''s pleasure, transcending mere legal obligation to achieve spiritual purification and social justice. This thesis is built upon exhaustive documentation from three foundations: Quranic exegesis demonstrating divine commands for charity, hadith analysis revealing prophetic guidance on charitable practice, and jurisprudential reasoning (*Usul al-Fiqh*) that distinguishes between mandatory (*Zakat*, *Khums*) and voluntary charitable obligations. The work grounds its argument in critical analysis of key Quranic verses on *Qard Hasan* (beautiful loan to Allah) and systematic examination of the eight categories of charitable recipients, while addressing contemporary applications in modern Islamic economics. Bahr Al-Ulum''s comprehensive approach transforms charitable giving from mere legal obligation into a sophisticated spiritual practice, offering a complete framework for understanding Islamic economic ethics and achieving both worldly prosperity and spiritual salvation.'
WHERE id = 'a75c00c8-42da-4421-a0ed-f11d2c0de535';