-- SQL Enrichment for Dalail al-Imam (Dala'il al-Imama)
-- Book ID: dddb5e13-e430-41fd-9e5d-b5cdf7c72f2a
-- Author: al-Tabari (though attribution disputed)
-- Generated by Islamic Text Processing Agent 7

UPDATE books 
SET 
    title_alias = 'Dala''il al-Imama',
    keywords = ARRAY[
        'Imams biography',
        'Fatima al-Zahra',
        'Infallible Imams',
        'Shia hagiography',
        'Islamic miracles',
        'Ahl al-Bayt',
        'Prophetic family',
        'Imam virtues',
        'Shia literature',
        'Early Islamic history',
        'Biographical traditions',
        'Miraculous accounts',
        'Imam identification',
        'Fadak incident',
        'Imam al-Mahdi',
        'Musnad Fatima',
        'Imam companions',
        'Ring inscriptions',
        'Imam genealogy',
        'Shia sources'
    ],
    description = 'A comprehensive biographical work containing the lives, virtues, and miracles of Lady Fatima (a) and the twelve Infallible Imams. The text follows a structured format for each Imam including identification, sobriquets, mother, close companions, engraved words on their rings, children, and miraculous accounts. The biography of Lady Fatima covers her birth, the meaning of Muhadditha, emigration, marriage details, the Fadak incident, her supplication, will, and prophetic dreams. Though traditionally attributed to al-Tabari, modern scholarship suggests this work was written by an unknown author in the early 5th/11th century, likely in Baghdad. The text serves as an important source in Shia literature for understanding the biographical traditions and hagiographical accounts of the Prophet''s family, though some narrations contain exaggerated content (ghuluw) attributing supernatural abilities to the Imams.',
    updated_at = NOW()
WHERE id = 'dddb5e13-e430-41fd-9e5d-b5cdf7c72f2a';

-- Verification query
SELECT id, title, title_alias, array_length(keywords, 1) as keyword_count, 
       length(description) as description_length, updated_at
FROM books 
WHERE id = 'dddb5e13-e430-41fd-9e5d-b5cdf7c72f2a';