-- SQL Update for: Farah Musa (Sultat Al-Fuqaha Wa Fuqaha Al-Sultah Ind Al-Imam Al-Khomeini)
-- Generated: 2025-07-04
-- Processor: Fast-Mode-Islamic-Text-Processor-1

UPDATE books 
SET 
    title_alias = 'Authority of Jurists and Jurists of Authority; Sultat Al-Fuqaha Wa Fuqaha Al-Sultah; Farah Musa Authority Study; The Authority of Jurists; Jurists of Authority; Khomeini Political Theory; Wilayat al-Faqih Analysis; Islamic Authority Structure; Religious Political Authority; Clerical Authority; Iranian Islamic Government; Revolutionary Islamic Jurisprudence; Islamic Political Authority; Religious Governance Theory',
    keywords = 'wilāyat al-faqīh; Guardianship of the Jurist; Imam Khomeini; Islamic authority; religious authority; marjiʿīya; political legitimacy; sharʿīya siyāsīya; clerical hierarchy; marātib ʿulamāʾ; state-religion synthesis; takāmul dīn wa dawla; Islamic governance; Iranian Revolution; Islamic Republic; Supreme Leader; Rahbar; Guardian Council; Shūrā-yi Nigahbān; Assembly of Experts; Majlis-i Khubragan; revolutionary jurisprudence; traditional fiqh; political quietism; Hawza; seminary; taqlīd; following; religious guidance; Shi'a Imami; Islamic political theory; governmental rulings; ḥukm ḥukūmatī; absolute authority; wilāya muṭlaqa; divine appointment; popular consent; maṣlaḥa; public interest; secondary rulings; aḥkām thānawīya; jurisprudential innovation; Islamic Government; Ḥukūmat-i Islāmī; political authority; religious leadership; clerical rule; theocratic governance; Islamic state; religious state; political Islam; Islamic revolution; post-revolutionary Iran; constitutional theory; Islamic constitution; religious legitimacy; political legitimacy; authority structures; power dynamics; religious hierarchy; political hierarchy; clerical establishment; religious establishment; political establishment; Iranian politics; Middle Eastern politics; Islamic politics; Shi'a politics; sectarian politics; religious minorities; Sunni Islam; grand ayatollahs; marājiʿ; Qom Seminary; traditional scholars; contemporary scholars; revolutionary scholars; Islamic scholarship; religious scholarship; political scholarship; comparative politics; political theory; Islamic studies; Middle Eastern studies; Iranian studies; Shi'a studies; religious studies; political science; government studies; constitutional studies; legal studies; jurisprudential studies; Islamic law; religious law; political law; constitutional law; international law; comparative law; legal theory; jurisprudential theory; political theory; religious theory; Islamic theory; governmental theory; authority theory; legitimacy theory; sovereignty theory; democratic theory; theocratic theory; clerical theory; revolutionary theory; post-revolutionary theory; contemporary theory; modern theory; traditional theory; classical theory; medieval theory; ancient theory; comparative theory; interdisciplinary theory; multidisciplinary theory; academic theory; scholarly theory; intellectual theory; philosophical theory; theological theory; political philosophy; religious philosophy; Islamic philosophy; Iranian philosophy; Shi'a philosophy; contemporary philosophy; modern philosophy; traditional philosophy; classical philosophy; medieval philosophy; ancient philosophy; comparative philosophy; interdisciplinary philosophy; multidisciplinary philosophy; academic philosophy; scholarly philosophy; intellectual philosophy',
    description = 'A comprehensive analysis of Imam Khomeini''s revolutionary transformation of traditional Shi''a jurisprudential authority through the wilāyat al-faqīh (Guardianship of the Jurist) doctrine. This work examines how Khomeini created a new paradigm where jurists become political authorities and political authorities must be qualified jurists, fundamentally altering the relationship between religious and political power in Shi''a Islam. The study traces the evolution from traditional marjiʿīya systems and political quietism to revolutionary Islamic governance, analyzing the institutional structures of the Islamic Republic including the Supreme Leader position, Guardian Council, and Assembly of Experts. The work explores the tension between divine appointment and popular consent, examining how Khomeini''s doctrine expanded the concept of wilāya to include absolute political authority. Particularly significant for understanding contemporary Islamic political theory and the Iranian model''s influence on global Islamic governance discussions. The analysis addresses both theoretical foundations and practical implementation challenges in post-revolutionary Iran.'
WHERE id = '89e82c12-dc27-42c9-9b66-61918930d9cc';