-- Enrichment for Ibn Taymiyyah by Saeib Abdul Hamid
-- UUID: c21c97d8-4014-468a-9e63-301813512d7f
-- Generated by Quality Assurance Validator (Agent 4)

UPDATE books SET 
  title_alias = 'Ibn Taymiyyah; Taqi al-Din Ahmad ibn Taymiyyah; Ibn Taymiyya; Ibn Taimiyya; Ahmad ibn Taymiyyah; Shaykh al-Islam Ibn Taymiyyah; The Controversial Scholar; Ibn Taymiyyah Critique; Anti-Shia Polemicist; Hanbali Theologian',
  keywords = ARRAY[
    'Ibn Taymiyyah', 'Taqi al-Din Ahmad', 'Hanbali school', 'Medieval Islam', 'Islamic theology', 'Kalam',
    'Anti-Shia polemics', 'Minhaj al-Sunnah', 'Sectarian polemics', 'Takfir', 'Excommunication', 'Theological exclusion',
    'Anthropomorphism', 'Tajsim', 'Divine attributes', 'Literal interpretation', 'Ash''ari theology', 'Salafi movement',
    'Wahhabism', 'Salafi ideology', 'Sectarian hostility', 'Theological controversy', 'Medieval scholarship',
    'Islamic intellectual history', 'Mongol invasions', 'Political theology', 'Religious authority', 'Scholarly integrity',
    'Biographical critique', 'Theological analysis', 'Historical assessment', 'Sectarian conflict', 'Contemporary sectarianism',
    'Fabricated traditions', 'Source criticism', 'Exegetical method', 'Quranic interpretation', 'Hadith methodology',
    'Theological methodology', 'Sectarian bias', 'Religious discourse', 'Islamic scholarship', 'Constructive dialogue',
    'Sectarian exclusivism', 'Theological debate', 'Critical evaluation', 'Historical consequences', 'Modern influence',
    'Sunni-Shia relations', 'Polemical literature', 'Counter-polemics', 'Theological legacy', 'Controversial figures'
  ],
  description = 'A critical biographical analysis examining the theological positions and sectarian impact of the controversial 13th-14th century Islamic scholar Ibn Taymiyyah. Saeib Abdul Hamid provides a comprehensive critique of Ibn Taymiyyah''s anti-Shia polemics, anthropomorphic theology, and tendency toward takfir, while analyzing how his positions influenced later Salafi movements and continue to fuel contemporary sectarian conflicts. The work serves as both historical assessment and cautionary study on the dangers of theological extremism.'
WHERE id = 'c21c97d8-4014-468a-9e63-301813512d7f';