-- Enrichment for Ithbat al-Imamah by Sayyidna Ahmad ibn Ibrahim al-Nisaburi
-- UUID: ba310963-5cef-41b6-9c26-c318dd2f7cdd
-- Generated by Quality Assurance Validator (Agent 4)

UPDATE books SET 
  title_alias = 'Ithbat al-Imamah; Proving the Imamate; Ithbat al Imamah; Proof of the Imamate; Establishing the Imamate; Evidence for the Imamate; Demonstration of Imamate; Rational Proofs for Imamate; Divine Appointment Proofs; Imamah Evidence',
  keywords = ARRAY[
    'Ithbat', 'Proof', 'Imamah', 'Imamate', 'Divine appointment', 'Nass', 'Succession', 'Leadership',
    'Rational proof', 'Burhan Aqli', 'Textual evidence', 'Dalil Naqli', 'Theological demonstration', 'Apologetics',
    'Shia theology', 'Imami theology', 'Classical Shia', 'Divine grace', 'Lutf', 'Continuous guidance',
    'Rational necessity', 'Wujub Aqli', 'Infallibility', 'Ismah', 'Divine guidance', 'Spiritual authority',
    'Ali ibn Abi Talib', 'Succession to Prophet', 'Ghadir Khumm', 'Hadith al-Thaqalayn', 'Hadith al-Manzilah',
    'Ayat al-Wilayah', 'Ayat al-Tabligh', 'Ayat al-Ikmal', 'Quranic evidence', 'Prophetic traditions',
    'Twelve Imams', 'Ahl al-Bayt', 'Wasiyyah', 'Testament', 'Chain of Imamate', 'Khilafah', 'Caliphate',
    'Temporal rule', 'Spiritual leadership', 'Religious authority', 'Comprehensive knowledge', 'Ilm Ladunni',
    'Sunni objections', 'Ijma', 'Consensus', 'Taqiyyah', 'Precautionary dissimulation', 'Political circumstances',
    'Theological proof', 'Systematic argumentation', 'Apologetic literature', 'Islamic jurisprudence', 'Kalam'
  ],
  description = 'A systematic theological treatise presenting rational and textual proofs for the divine appointment of the Imamate in Islam. Sayyidna Ahmad ibn Ibrahim al-Nisaburi combines philosophical argumentation with Quranic and prophetic evidence to demonstrate the logical necessity and scriptural basis for continuous divine guidance through infallible Imams. The work addresses objections while establishing the essential attributes and divine origin of the Imamate as distinct from temporal caliphate.'
WHERE id = 'ba310963-5cef-41b6-9c26-c318dd2f7cdd';