-- SQL Enrichment for Kitab Al-Raja_ah by Al-Shaykh Ahmad Al-Ahsa_i
-- Book ID: d7fae93f-1e34-4784-8387-4348a7021e20
-- Generated by Islamic Text Processing Agent 5

UPDATE books SET
    title_alias = 'Al-''iṣma wa l-rij''a (The Infallibility and Return)',
    keywords = ARRAY[
        'Raja''ah', 'Return', 'Raj''a', 'Eschatology', 'Infallibility', '''Isma',
        'Twelver Shi''a', 'Shaykhiyya', 'Imam al-Mahdi', 'Occultation', 'Ghayba',
        'Resurrection', 'End Times', 'Theological Treatise', 'Doctrinal Response',
        'Islamic Theology', 'Shi''a Doctrine', 'Prophetic Infallibility', 'Imamic Authority',
        'Eschatological Beliefs', 'Religious Authority', 'Theological Debate',
        'Jawāmi'' al-kalim', 'Spiritual Return', 'Divine Justice'
    ],
    description = 'A theological treatise by Shaykh Ahmad al-Ahsa''i addressing the fundamental Shi''a doctrines of ''isma (infallibility of the Prophet and Imams) and raja''ah (the return of certain believers to this world after the reappearance of Imam al-Mahdi). Written as a response to Muhammad ''Ali Mirza Dawlatshah''s theological inquiries, this work represents a significant contribution to Shaykhiyya theological discourse on eschatological matters. The treatise explores the concepts of prophetic and imamic infallibility within the context of Twelver Shi''a belief, while examining the doctrine of raja''ah as it relates to the anticipated return of the Hidden Imam and the establishment of divine justice. This work exemplifies al-Ahsa''i''s distinctive theological approach that would later influence the development of the Shaykhiyya school and contribute to 19th-century Islamic theological debates on authority, resurrection, and the nature of religious leadership during the period of occultation.'
WHERE id = 'd7fae93f-1e34-4784-8387-4348a7021e20';