-- SQL Enrichment for Ma_at Kalimah (Mi'at Kalimah / Minhaj al-'arifin)
-- Book ID: c76dbc16-6b1f-46dd-8c45-3c437a7b6df7
-- Author: Bin Maytham Al-Baharani (Ibn Maytham al-Bahrani)
-- Generated by Islamic Text Processing Agent 7

UPDATE books 
SET 
    title_alias = 'Mi''at Kalimah / Minhaj al-''Arifin',
    keywords = ARRAY[
        'Imam Ali sayings',
        'Nahj al-Balagha',
        'Islamic philosophy',
        'Shia commentary',
        'hundred words',
        'spiritual guidance',
        'Islamic mysticism',
        'Bahrani school',
        'theological commentary',
        'Amir al-Mu''minin',
        'Islamic ethics',
        'gnostic path',
        'spiritual aphorisms',
        'Islamic wisdom',
        'Shia theology',
        'philosophical commentary',
        'mystical interpretation',
        'Islamic spirituality',
        'Ahl al-Bayt teachings',
        'medieval Islamic thought'
    ],
    description = 'A theological and philosophical commentary on the collection of one hundred sayings attributed to Imam Ali, originally compiled by al-Jahiz and known as "Mi''at Kalimah li-Amir al-Mu''minin." Ibn Maytham al-Bahrani''s commentary, titled "Minhaj al-''Arifin" (The Path of the Gnostics), represents a sophisticated integration of Islamic theology, philosophy, and mysticism characteristic of the Bahrani school of thought. The work follows Ibn Maytham''s distinctive approach of grounding arguments primarily in reason rather than revelation, similar to his methodology in other major works. As a 13th-century Shia scholar renowned for his expertise in ''ilm al-Kalam (theology), Ibn Maytham provides detailed exegesis of these aphoristic teachings, emphasizing their philosophical and spiritual dimensions. The commentary serves as both a theological treatise and a guide for spiritual seekers, reflecting the author''s synthesis of rational theology with mystical insight that influenced subsequent generations of Islamic scholars.',
    updated_at = NOW()
WHERE id = 'c76dbc16-6b1f-46dd-8c45-3c437a7b6df7';

-- Verification query
SELECT id, title, title_alias, array_length(keywords, 1) as keyword_count, 
       length(description) as description_length, updated_at
FROM books 
WHERE id = 'c76dbc16-6b1f-46dd-8c45-3c437a7b6df7';