-- Enrichment for: Nabiy wa Wasiy Wa Wasaya by Shaykh Ali Haydar al-Mu'ayyad
-- UUID: a8b82c84-3c2c-43a0-aeeb-b30c748eaa71
-- Agent: agent-metadata-expert-002 (Metadata Enrichment Expert)
-- Generated: 2025-07-04

UPDATE books SET 
  title_alias = 'The Prophet and the Successor and the Testaments; Nabiy wa Wasiy Wa Wasaya; Al-Nabiy wal-Wasiy wal-Wasaya; Prophet and Guardian and Wills; The Prophet and His Successor and Their Testaments; Nabiy Wasiy Wasaya; The Prophetic Testament System; Prophet Successor Testament; Al-Nabiy wal-Wasiy; The Divine Succession and Testament',
  keywords = ARRAY[
    'Nubuwwa', 'Prophethood', 'Wasiya', 'Testament', 'Succession', 'Wasiy', 'Successor', 'Divine appointment', 'Nass', 'Prophetic succession', 'Imamah', 'Imamate', 'Wilayah', 'Guardianship', 'Ghadir Khumm', 'Hadith al-Thaqalayn', 'Hadith al-Manzilah', 'Ahl al-Bayt', 'Ali ibn Abi Talib', 'Khalifah', 'Caliphate', 'Khilafah', 'Ijma', 'Consensus', 'Shia theology', 'Imami doctrine', 'Succession theology', 'Prophetic traditions', 'Hadith', 'Tafsir', 'Quranic exegesis', 'Kalam', 'Theology', 'Ismah', 'Infallibility', 'Divine guidance', 'Hidaya', 'Religious authority', 'Islamic leadership', 'Sunnah', 'Prophetic example', 'Wasaya', 'Testaments', 'Divine ordinance', 'Spiritual succession', 'Irshad', 'Guidance', 'Aqidah', 'Belief', 'Usul al-Din', 'Principles of faith', 'Ijtihad', 'Religious interpretation', 'Marjaiyyah', 'Religious authority', 'Tawhid', 'Divine unity', 'Adalat', 'Justice', 'Maad', 'Resurrection', 'Eschatology', 'End times', 'Rajaa', 'Return', 'Mahdi', 'Awaited Imam', 'Ghaybah', 'Occultation', 'Taqiyya', 'Precautionary dissimulation', 'Marja', 'Source of emulation', 'Fiqh', 'Jurisprudence', 'Ahkam', 'Religious rulings', 'Ibadat', 'Worship', 'Muamalat', 'Transactions', 'Akhlaq', 'Ethics', 'Tasawwuf', 'Sufism', 'Spirituality', 'Marifah', 'Gnosis', 'Irfan', 'Mysticism'
  ],
  description = 'A comprehensive theological treatise examining the Islamic doctrine of prophetic succession and testament, authored by Shaykh Ali Haydar al-Mu''ayyad. The work systematically explores the foundational concepts of prophethood (Nubuwwa), divine succession (Wasiya), and the institutional framework of religious testaments (Wasaya) within Islamic theology. Drawing from Quranic exegesis, prophetic traditions, and rational argumentation, the book presents a detailed analysis of how divine appointment operates through testament rather than human election. The study encompasses the theological foundations of the Imamate, the distinction between political and spiritual succession, and the continuous guidance system established through prophetic testament. Key themes include the Event of Ghadir Khumm, the concept of divinely appointed successors (Awsiya), and the comparative analysis of succession models across prophetic traditions. The work serves as a significant contribution to Shia Imami theology, demonstrating the systematic implementation of divine guidance through appointed religious authority and the preservation of authentic Islamic teachings through the testament system.'
WHERE id = 'a8b82c84-3c2c-43a0-aeeb-b30c748eaa71';