-- Enrichment for: Sirat al-A'emma by Hisham Ma'ruf al-Husayni
-- UUID: fec714d3-0554-4f30-be6f-605bf50346e0
-- Agent: agent-metadata-expert-002 (Metadata Enrichment Expert)
-- Generated: 2025-07-04

UPDATE books SET 
  title_alias = 'Biographies of the Imams; Sirat al-Aimma; Sirat al-A''emma; Lives of the Twelve Imams; The Imams'' Biographies; Sirat al-Aimma al-Ithna Ashar; Biographies of the Infallibles; Lives of Ahl al-Bayt; Sirat Ahl al-Bayt; The Twelve Imams Lives; Biography of the Guided Imams; Sirat al-Aimma al-Athar',
  keywords = ARRAY[
    'Sirat', 'Biography', 'Imams', 'Aimma', 'Twelve Imams', 'Ithna Ashar', 'Shia Imams', 'Ahl al-Bayt', 'Fourteen Infallibles', 'Masumin', 'Ali ibn Abi Talib', 'Hasan ibn Ali', 'Husayn ibn Ali', 'Ali ibn Husayn', 'Zayn al-Abidin', 'Muhammad al-Baqir', 'Jafar al-Sadiq', 'Musa al-Kazim', 'Ali al-Rida', 'Muhammad al-Jawad', 'Ali al-Hadi', 'Hasan al-Askari', 'Muhammad al-Mahdi', 'Imam al-Mahdi', 'Mahdi', 'Ghaybah', 'Occultation', 'Karbala', 'Ashura', 'Ghadir Khumm', 'Wilayah', 'Guardianship', 'Imamate', 'Imamah', 'Nass', 'Divine appointment', 'Succession', 'Caliphate', 'Khilafah', 'Fadail', 'Virtues', 'Karamat', 'Miracles', 'Shahadah', 'Martyrdom', 'Tarajim', 'Biographical literature', 'Hagiography', 'Riwayah', 'Narration', 'Hadith', 'Prophetic traditions', 'Sunnah', 'Najaf', 'Karbala', 'Mashhad', 'Samarra', 'Kazimayn', 'Shrine cities', 'Pilgrimage', 'Ziyarah', 'Taqiyyah', 'Precautionary dissimulation', 'Wakalah', 'Representative system', 'Nuwwab Arbaa', 'Four representatives', 'Sahifa Sajjadiyya', 'Supplications', 'Nahj al-Balaghah', 'Sermons', 'Khutab', 'Speeches', 'Fiqh Jafari', 'Jafari jurisprudence', 'Islamic law', 'Scholarly contributions', 'Education', 'Teaching', 'Students', 'Scholars', 'Umayyad', 'Abbasid', 'Political persecution', 'Resistance', 'Spiritual authority', 'Religious leadership', 'Divine guidance', 'Infallibility', 'Ismah', 'Intercession', 'Shafaah', 'Devotional practice', 'Spiritual guidance', 'Religious instruction', 'Muharram', 'Commemoration', 'Mourning rituals', 'Azadari', 'Majlis', 'Religious gathering'
  ],
  description = 'A comprehensive biographical encyclopedia documenting the lives, teachings, and spiritual legacy of the twelve Shia Imams, authored by Hisham Ma''ruf al-Husayni. This work systematically presents the biographies of each Imam from Ali ibn Abi Talib through the awaited Imam al-Mahdi, combining historical narration with devotional purpose. The book explores the theological foundations of the Imamate, the concept of divine appointment and succession, and the continuous guidance provided through the Ahl al-Bayt. Each biographical account includes the Imam''s historical context, major teachings, scholarly contributions, persecution experiences, and martyrdom circumstances. Key themes encompass the Event of Ghadir Khumm, the Battle of Karbala, the development of Shia jurisprudence, the occultation period, and the shrine cities that became centers of pilgrimage. The work serves as both historical documentation and spiritual instruction, preserving the intellectual and devotional legacy of the Imams for contemporary Shia religious education and practice.'
WHERE id = 'fec714d3-0554-4f30-be6f-605bf50346e0';