-- Enrichment for: Tarikh al-Tashri' al-Muqarn by Shaykh Salim Safar
-- UUID: a82c95eb-450e-43c4-89db-158a770fb80a
-- Agent: agent-metadata-expert-002 (Metadata Enrichment Expert)
-- Generated: 2025-07-04

UPDATE books SET 
  title_alias = 'History of Comparative Legislation; Tarikh al-Tashri al-Muqarn; Comparative History of Islamic Law; Islamic Legal History Comparative Study; History of Islamic Jurisprudence Comparison; Muqaran Legal History; Comparative Islamic Legislation History; Tarikh Tashri Muqaran; Historical Comparative Jurisprudence; Islamic Legal Development History',
  keywords = ARRAY[
    'Tarikh al-Tashri', 'History of legislation', 'Muqarn', 'Comparative', 'Islamic law', 'Fiqh', 'Jurisprudence', 'Legal history', 'Comparative jurisprudence', 'Madhab', 'Legal schools', 'Hanafi', 'Maliki', 'Shafi', 'Hanbali', 'Jafari', 'Shia jurisprudence', 'Sunni jurisprudence', 'Legal methodology', 'Usul al-Fiqh', 'Principles of jurisprudence', 'Quran', 'Sunnah', 'Hadith', 'Ijma', 'Consensus', 'Qiyas', 'Analogical reasoning', 'Ijtihad', 'Legal interpretation', 'Legal codification', 'Islamic legal development', 'Jurisprudential evolution', 'Legal scholarship', 'Fuqaha', 'Jurists', 'Legal sources', 'Masadir al-Ahkam', 'Islamic legal theory', 'Comparative law', 'Legal systems', 'Historical methodology', 'Legal historiography', 'Academic research', 'Scholarly analysis', 'Cross-school comparison', 'Methodological differences', 'Legal adaptation', 'Geographic variations', 'Political influence on law', 'Social context', 'Legal reform', 'Modern Islamic law', 'Contemporary jurisprudence', 'Legal modernization', 'Colonial impact', 'Legal codification movements', 'Integration with modern systems', 'Traditional law', 'Classical period', 'Medieval systematization', 'Early Islamic law', 'Prophetic legislation', 'Caliphate law', 'Umayyad law', 'Abbasid law', 'Ottoman law', 'Safavid law', 'Mughal law', 'Contemporary Muslim states', 'Legal education', 'Madrasah curriculum', 'Law schools', 'Legal training', 'Scholarly tradition', 'Academic study', 'Research methodology', 'Source criticism', 'Historical analysis', 'Comparative methodology', 'Objective scholarship'
  ],
  description = 'A comprehensive academic study examining the comparative history of Islamic legislation and jurisprudential development, authored by Shaykh Salim Safar. The work employs historical analysis and comparative methodology to document the evolution of Islamic legal systems across different schools, periods, and geographic regions. The book systematically analyzes the development of major legal schools including Hanafi, Maliki, Shafi, Hanbali, and Jafari jurisprudence, examining their methodological differences and practical applications. Key themes include the formation of legal methodology (Usul al-Fiqh), the influence of political and social contexts on legal development, cross-school scholarly exchange, and the adaptation of Islamic law to different cultural and geographic settings. The study encompasses the classical period of legal systematization, medieval codification efforts, and modern challenges including colonial impact and contemporary reform movements. The work serves as an important contribution to Islamic legal historiography, providing objective scholarly analysis of jurisprudential evolution without sectarian bias and demonstrating the rich diversity and adaptability of Islamic legal tradition throughout history.'
WHERE id = 'a82c95eb-450e-43c4-89db-158a770fb80a';