-- Enrichment for al-Imamah fi al-Islam by Dr. Arif Tamer
-- UUID: 8534b802-0a2f-4b1f-abf6-2a833dc34ffa
-- Generated by Quality Assurance Validator (Agent 4)

UPDATE books SET 
  title_alias = 'al-Imamah fi al-Islam; The Imamate in Islam; Al Imamah fi al Islam; Islamic Leadership; Leadership in Islam; The Imamah in Islam; Imamate in Islam; Al-Imamah fi Islam; Islamic Governance; Divine Leadership',
  keywords = ARRAY[
    'Imamah', 'Imamate', 'Islamic leadership', 'Caliphate', 'Khilafah', 'Wilayah', 'Guardianship', 
    'Divine appointment', 'Nass', 'Succession', 'Prophet Muhammad', 'Ali ibn Abi Talib', 'Rashidun Caliphate',
    'Shura', 'Consultation', 'Bay''ah', 'Oath of allegiance', 'Sunni Islam', 'Shia Islam', 'Twelver Shia',
    'Ismah', 'Infallibility', 'Ulu al-Amr', 'Religious authority', 'Temporal authority', 'Spiritual leadership',
    'Islamic governance', 'Political theory', 'Theology', 'Kalam', 'Aqidah', 'Islamic doctrine',
    'Hadith al-Thaqalayn', 'Ayat al-Wilayah', 'Quranic exegesis', 'Tafsir', 'Prophetic traditions',
    'Hadith', 'Sunnah', 'Ulama', 'Islamic scholars', 'Religious establishment', 'Jurisprudence',
    'Fiqh', 'Islamic law', 'Constitutional theory', 'Muslim societies', 'Contemporary Islam',
    'Islamic political thought', 'Comparative religion', 'Sectarian differences', 'Unity and diversity'
  ],
  description = 'A comprehensive theological treatise examining the concept of Imamah (Islamic leadership) within the broader framework of Islamic governance. Dr. Arif Tamer presents a systematic analysis of divine appointment versus community selection in Islamic leadership, exploring both Sunni and Shia perspectives on legitimate succession after Prophet Muhammad. The work examines Quranic foundations, prophetic traditions, and rational theological arguments to establish the essential nature and divine mandate of Imamah as a system combining spiritual and temporal authority in Islamic societies.'
WHERE id = '8534b802-0a2f-4b1f-abf6-2a833dc34ffa';