-- Al-Isma Database Enrichment
-- Book UUID: 11a6711c-57dc-4f6a-80e6-8601f4648dfe
-- Processing Date: 2025-07-03
-- Agent: Islamic Text Processing Agent 2

UPDATE books 
SET 
    title_alias = 'Divine Infallibility; The Infallibility; Al Isma; Al-Ismah; Ismah; The Doctrine of Infallibility; Infallibility in Islam; Isma; Divine Protection from Error; Ismah wa Tahara; The Purification; Infallible Authority; Divine Sinlessness; Protection from Sin; Ahl al-Bayt Infallibility',
    keywords = ARRAY['Isma','Infallibility','Divine Protection','Sinlessness','Ismah','Prophetic Infallibility','Imamic Infallibility','Ahl al-Bayt','Purification','Ayat al-Tathir','Theological Treatise','Shia Doctrine','Sunni Doctrine','Kalam','Scholastic Theology','Aql','Rational Argumentation','Quranic Exegesis','Hadith Analysis','Religious Authority','Divine Guidance','Prophets','Imams','Lutf','Divine Grace','Hujja','Proof','Nass','Divine Appointment','Wilaya','Guardianship','Tabligh','Conveying Message','Tawfiq','Divine Success','Ijtihad','Legal Reasoning','Taqlid','Following Authority','Wilayat al-Faqih','Jurisprudence','Islamic Theology','Doctrinal Differences','Interfaith Relations','Comparative Religion','Mutazila','Ashari','Hadith al-Thaqalayn','Twelve Imams','Prophetic Traditions','Quranic Verses','Spiritual Authority','Legal Authority','Divine Law','Religious Leadership','Islamic Studies','Theological Discourse','Apologetics','Polemics','Sectarian Differences','Orthodox Islam','Mystical Dimensions','Spiritual Development','Contemporary Islamic Thought','Classical Theology','Medieval Islamic Philosophy','Religious Philosophy','Divine Attributes','Free Will','Determinism','Theodicy','Islamic Ethics','Moral Philosophy','Religious Epistemology','Revelation','Interpretation','Hermeneutics','Scriptural Authority','Tradition','Succession','Caliphate','Imamate','Political Theology','Religious Politics','Islamic Jurisprudence','Fiqh','Usul al-Fiqh','Principles of Jurisprudence','Religious Law','Divine Command Theory','Moral Authority','Ethical Leadership','Religious Exemplars','Spiritual Models','Devotional Literature','Worship','Ritual Purity','Spiritual Purification','Asceticism','Piety','Righteousness','Virtue Ethics','Character Development','Moral Psychology','Religious Experience','Mysticism','Sufism','Gnosis','Spiritual Knowledge','Esoteric Knowledge','Exoteric Knowledge','Religious Sciences','Islamic Philosophy','Theology','Doctrine','Belief','Faith','Iman','Islam','Muslim','Ummah','Community','Authority','Leadership','Guidance','Teaching','Education','Scholarship','Learning','Knowledge','Ilm','Wisdom','Hikmah','Truth','Haqq','Reality','Metaphysics','Ontology','Epistemology','Logic','Dialectics','Debate','Argumentation','Proof','Evidence','Testimony','Witness','Shahada','Martyrdom','Sacrifice','Devotion','Loyalty','Allegiance','Baya','Oath','Covenant','Promise','Commitment','Responsibility','Accountability','Judgment','Justice','Adl','Fairness','Equity','Balance','Moderation','Extremism','Fanaticism','Tolerance','Pluralism','Diversity','Unity','Harmony','Peace','Conflict','Resolution','Reconciliation','Dialogue','Conversation','Discussion','Discourse','Communication','Language','Arabic','Translation','Interpretation','Commentary','Exegesis','Tafsir','Hermeneutics','Linguistics','Philology','Literature','Poetry','Prose','Rhetoric','Eloquence','Oratory','Preaching','Sermon','Khutba','Perfect','Perfection','Completion','Fulfillment'],
    description = 'A comprehensive theological treatise on the Islamic doctrine of ''Isma (divine infallibility), examining the concept of divinely bestowed freedom from error and sin in Islamic religious leadership. This work systematically explores the theological foundations of infallibility through Quranic exegesis, hadith analysis, and rational argumentation, with particular emphasis on the Shi''a Imami perspective that extends infallibility beyond prophets to include the Twelve Imams and the Ahl al-Bayt. The text addresses the necessity of infallible guidance for the proper interpretation of divine law and spiritual leadership, while engaging with Sunni theological objections and providing detailed responses to various schools of Islamic thought. Through its methodical approach, the work demonstrates how divine infallibility serves as a cornerstone of Islamic theology, linking scriptural authority with practical religious guidance and establishing the framework for understanding legitimate religious authority in Islam.'
WHERE id = '11a6711c-57dc-4f6a-80e6-8601f4648dfe';