-- Enrichment SQL for al-Imamah wal-Khilafah (UUID: 3c964ae9-c544-445d-9564-c305f2f3f41c)
-- Author: Muqatil ibn Atiyah
-- Generated by Islamic-Text-Processor-7 on 2025-07-04

UPDATE books 
SET 
    title_alias = 'The Imamate and Caliphate; al-Imamah wal-Khilafah; Al Imamah wal Khilafah; Leadership and Succession in Islam; The Imamate and the Caliphate; Political Authority in Islam; Islamic Leadership Theory; Succession after the Prophet; Caliphate vs Imamate; The Question of Islamic Authority',
    
    keywords = ARRAY[
        'Imamah', 'Imamate', 'Khilafah', 'Caliphate', 'Islamic Leadership', 'Succession', 'Political Authority', 'Theological Authority', 'Wilayah', 'Guardianship', 'Nass', 'Divine Appointment', 'Ijma', 'Consensus', 'Ahl al-Bayt', 'Rashidun Caliphs', 'Abu Bakr', 'Umar ibn al-Khattab', 'Uthman ibn Affan', 'Ali ibn Abi Talib', 'Saqifah', 'Saqifah Bani Saida', 'Fadak', 'Fitna', 'Civil Wars', 'Prophetic Succession', 'Hadith al-Thaqalayn', 'Two Weighty Things', 'Ulil-Amr', 'Those in Authority', 'Ismah', 'Infallibility', 'Islamic Political Theory', 'Sunni', 'Shia', 'Fiqh', 'Islamic Law', 'Ijtihad', 'Religious Authority', 'Governance', 'Islamic State', 'Legitimacy', 'Political Islam', 'Early Islamic History', 'Muqatil ibn Atiyah', 'Theological Treatise', 'Political Treatise', 'Islamic Civilization', 'Muslim Community', 'Ummah'
    ],
    
    description = 'A comprehensive theological-political treatise examining the foundational principles that distinguish the Imamate (Imamah) from the Caliphate (Khilafah) as systems of Islamic governance. This scholarly work by Muqatil ibn Atiyah employs historical precedent analysis combined with theological argumentation from the Quran and Sunnah to explore the question of legitimate authority in Islamic civilization. The treatise systematically analyzes the theological foundations of authority, including divine appointment (Nass) versus community consensus (Ijma), the concept of infallibility (Ismah) as a criterion for leadership, and the role of Wilayah (Guardianship) in its political and spiritual dimensions. Through detailed examination of pivotal historical events such as the Saqifah incident, the succession of the four Rashidun Caliphs, and early Islamic controversies, the work provides a comparative analysis of Sunni and Shia theoretical frameworks for understanding Islamic leadership. The treatise addresses the jurisprudential consequences of different succession methodologies and their impact on Islamic law development, making it a significant contribution to Islamic political theory and the ongoing discourse on authority, legitimacy, and governance in the Muslim world.'

WHERE id = '3c964ae9-c544-445d-9564-c305f2f3f41c';

-- Verify the update was successful
SELECT id, title, title_alias, array_length(keywords, 1) as keyword_count, 
       CASE WHEN description IS NOT NULL THEN 'Updated' ELSE 'No Description' END as description_status
FROM books 
WHERE id = '3c964ae9-c544-445d-9564-c305f2f3f41c';