-- Islamic Text Processor 3 - Book Enrichment
-- Book: al-Jawami_ wal-Fawariq bayna al-Sunnah wal-Shi_ah
-- Author: Muhammad Jawad Mughniyah
-- Processing Date: 2025-07-04

UPDATE books 
SET 
    title_alias = 'Al-Jawami wal-Fawariq bayna al-Sunnah wal-Shiah; The Commonalities and Differences between Sunni and Shia; Al Jawami wal Fawariq; Commonalities and Differences; Sunni Shia Comparative Study; Islamic Sectarian Analysis; Unity and Differences in Islam; Mughniyah Comparative Study; Al-Jawami wa al-Fawariq; The Similarities and Differences; Sunni Shia Dialogue; Islamic Unity Study',
    
    keywords = ARRAY[
        'Muhammad Jawad Mughniyah', 'Sunni Shia relations', 'Islamic sectarian studies', 'Comparative Islamic theology', 'Interfaith dialogue', 'Islamic unity', 'Ummah', 'Sectarian differences', 'Theological commonalities', 'Shia Imami scholarship', 'Lebanese Islamic scholarship', 'Caliphate vs Imamate', 'Succession to Prophet', 'Ahl al-Bayt', 'Rightly-Guided Caliphs', 'Ghadir Khumm', 'Islamic jurisprudence', 'Fiqh differences', 'Madhahib', 'Usul al-Din', 'Furu al-Din', 'Tawhid', 'Nubuwwah', 'Maad', 'Salah', 'Zakat', 'Hajj', 'Sawm', 'Mutah', 'Temporary marriage', 'Turbah', 'Prostration stone', 'Sahaba', 'Companions', 'Adalah al-Sahabah', 'Ismat al-Aimmah', 'Infallible Imams', 'Ijtihad', 'Taqlid', 'Kitab', 'Sunnah', 'Hadith collections', 'Kutub al-Sittah', 'Kutub al-Arbaah', 'Primary sources', 'Fitna', 'Battle of Siffin', 'Karbala', 'Arbitration', 'Tahkim', 'Matam', 'Umar ibn al-Khattab', 'Aisha', 'Battle of the Camel', 'Ikhtilaf', 'Scholarly differences', 'Quranic foundation', 'Prophetic tradition', 'Islamic dialogue', 'Reconciliation', 'Bridge-building', 'Sectarian analysis', 'Theological anthropology', 'Community consensus', 'Ijma', 'Shura', 'Consultative succession', 'Nass', 'Textual appointment', 'Wilayah', 'Guardianship', 'Inheritance laws', 'Ritual law', 'Prayer practices', 'Legal authority', 'Masadir al-Ahkam', 'Historical analysis', 'Contemporary dialogue', 'Mutual respect', 'Understanding', 'Scholarly objectivity', 'Balanced methodology', 'Unity through diversity', 'Islamic brotherhood'
    ],
    
    description = 'A landmark comparative study by Lebanese Shia scholar Muhammad Jawad Mughniyah examining the theological commonalities and differences between Sunni and Shia Islam. This comprehensive work systematically analyzes shared fundamentals (al-Jawami) including Tawhid, Nubuwwah, and ritual practices, while objectively examining key differences (al-Fawariq) in succession theory, jurisprudential practices, and historical interpretation. Mughniyah employs balanced methodology using primary sources from both traditions to promote interfaith dialogue within Islam, making this essential reading for understanding Islamic sectarian relations and unity-building approaches. The work addresses critical issues including the Caliphate versus Imamate, the authority of Companions, temporary marriage, prayer practices, and the theological implications of early Islamic history, particularly Ghadir Khumm and Karbala. Notable for its scholarly objectivity and contribution to Islamic unity discourse.'

WHERE id = '09e4b2b4-6f91-4b67-89dd-20a82acff387';