-- Enrichment for: al-Kharaj wal-Jara'ih by al-Rawandi
-- UUID: 25188969-db3d-42d6-b19a-39bdfbfb9e86
-- Agent: agent-metadata-expert-002 (Metadata Enrichment Expert)
-- Generated: 2025-07-04

UPDATE books SET 
  title_alias = 'Land Tax and Injuries; al-Kharaj wal-Jaraaih; Islamic Taxation and Penalties; Land Revenue and Bodily Injuries; Kharaj and Criminal Penalties; Islamic Fiscal and Penal Law; Taxation and Legal Penalties; Al-Kharaj wal-Jaraaih; Revenue and Injury Law; Islamic Administrative Law',
  keywords = ARRAY[
    'Kharaj', 'Land tax', 'Islamic taxation', 'Jaraaih', 'Bodily injuries', 'Penalties', 'Criminal law', 'Fiscal law', 'Islamic law', 'Fiqh', 'Administrative law', 'State revenue', 'Tax collection', 'Land tenure', 'Conquered territories', 'Ushr', 'Diyya', 'Blood money', 'Qisas', 'Retaliation', 'Tazir', 'Discretionary penalties', 'Islamic governance', 'Public finance', 'State administration', 'Legal penalties', 'Compensation', 'Islamic economics', 'Revenue system', 'Tax policy', 'Legal assessment', 'Court procedures', 'Administrative justice', 'Islamic state', 'Caliphate administration', 'Legal methodology', 'Usul al-Fiqh', 'Jurisprudential analysis', 'Classical Islamic law', 'Legal precedents', 'Quranic sources', 'Prophetic traditions', 'Hadith', 'Legal scholarship', 'Fuqaha', 'Jurists', 'Islamic legal theory', 'Practical law', 'Applied jurisprudence', 'Legal implementation', 'Government policy', 'Public law', 'Financial law', 'Criminal penalties', 'Legal compensation', 'Injury assessment', 'Legal damages', 'Court decisions', 'Legal procedures', 'Administrative procedures', 'Revenue collection', 'Tax administration', 'Legal enforcement', 'Judicial system', 'Islamic courts', 'Legal practice', 'Traditional law', 'Classical jurisprudence', 'Legal integration', 'Unified legal system', 'Comprehensive law', 'Practical governance', 'Legal application', 'Administrative implementation'
  ],
  description = 'A classical Islamic jurisprudential treatise examining the integration of fiscal and penal law within Islamic governance, authored by al-Rawandi. The work systematically addresses two fundamental aspects of Islamic legal administration: the Kharaj system of land taxation and the Jaraaih framework for bodily injuries and legal penalties. The book provides comprehensive coverage of Islamic taxation principles, including the assessment and collection of land revenue from conquered territories, the distinction between Ushr and Kharaj lands, and the administrative structures necessary for fiscal management. The treatment of Jaraaih encompasses the classification of bodily injuries, calculation of Diyya (blood money), principles of Qisas (retaliation), and discretionary penalties (Tazir). The work demonstrates how these seemingly separate legal domains function as integrated components of Islamic governance, showing the practical application of Islamic law in state administration. This treatise serves as an important source for understanding classical Islamic approaches to public finance, criminal law, and administrative justice, providing valuable insights into the practical implementation of Islamic legal principles in governmental contexts.'
WHERE id = '25188969-db3d-42d6-b19a-39bdfbfb9e86';