-- Enrichment for La Takhun Allah wal-Rasul by Sabah Ali al-Bayati
-- UUID: e3b720c3-a2e3-4087-892d-de0807725fd6
-- Generated by Quality Assurance Validator (Agent 4)

UPDATE books SET 
  title_alias = 'La Takhun Allah wal-Rasul; Do Not Betray Allah and the Prophet; La Takhun Allah wal Rasul; Do Not Betray Allah and His Messenger; Don''t Betray Allah and the Prophet; La Takhun Allah; Loyalty to Allah and Prophet; Faithfulness to Divine Covenant; Religious Loyalty; Avoiding Betrayal',
  keywords = ARRAY[
    'Betrayal', 'Khiyanah', 'Loyalty', 'Faithfulness', 'Covenant', 'Mithaq', 'Amanah', 'Trust',
    'Divine covenant', 'Prophetic loyalty', 'Wala', 'Religious ethics', 'Islamic morality', 'Moral guidance',
    'Ethical conduct', 'Wa''z', 'Irshad', 'Moral exhortation', 'Spiritual guidance', 'Religious responsibility',
    'Community obligation', 'Ummah', 'Collective responsibility', 'Individual accountability', 'Faith and action',
    'Iman', 'Amal', 'Righteous deeds', 'Hypocrisy', 'Nifaq', 'Sincere faith', 'Tawhid', 'Monotheism',
    'Shirk', 'Polytheism', 'Bid''ah', 'Innovation', 'Sunnah', 'Prophetic tradition', 'Obedience',
    'Divine command', 'Prophetic mission', 'Spiritual consequences', 'Worldly consequences', 'Accountability',
    'Judgment Day', 'Tawbah', 'Repentance', 'Forgiveness', 'Divine mercy', 'Dhikr', 'Remembrance',
    'Righteous companionship', 'Religious education', 'Moral instruction', 'Community guidance'
  ],
  description = 'A moral exhortation treatise examining the ethical imperative of loyalty and faithfulness to Allah and His Prophet. Sabah Ali al-Bayati presents a comprehensive guide to avoiding various forms of betrayal while cultivating covenant fidelity through proper understanding of trust, responsibility, and religious commitment. The work combines Quranic verses and prophetic traditions to provide practical guidance for maintaining spiritual and ethical integrity in both individual and community contexts.'
WHERE id = 'e3b720c3-a2e3-4087-892d-de0807725fd6';