-- SQL Enrichment for Li-Kayla Tatanaaza_u (لِكَيْلَا تَتَنَازَعُوا)
-- Author: Ayatollah Al-Udhma Al-Imam Sayyid Muhammad al-Husayni al-Shirazi
-- Generated: 2025-07-03

UPDATE books 
SET 
    title_alias = 'So That You May Not Dispute; Li-Kayla Tatanaaza_u; Lest You Dispute; Li Kayla Tatanaaza_u; So That You Will Not Quarrel; Preventive Jurisprudence Guide; Islamic Unity Methodology; Conflict Prevention in Islamic Law; Li-Kayla Tatanaazau; Shirazi Unity Treatise; Jurisprudential Harmony Guide; Community Cohesion Manual; Li Kayla Tatanaza_u; Dispute Prevention Framework; Islamic Legal Methodology; Marja Unity Guidelines; Scholarly Discourse Ethics; Preventive Fiqh Principles; Religious Harmony Treatise; Li-Kayla Tatanaazu',
    keywords = ARRAY['Islamic jurisprudence', 'Shi''a fiqh', 'preventive methodology', 'religious unity', 'community harmony', 'dispute resolution', 'conflict prevention', 'usul al-fiqh', 'marja authority', 'scholarly discourse', 'jurisprudential ethics', 'Islamic law', 'Grand Ayatollah Shirazi', 'Shirazi school', 'religious authority', 'legal methodology', 'community cohesion', 'ijma consensus', 'aql reason', 'ijtihad independent reasoning', 'maslaha public interest', 'Islamic legal theory', 'sectarian harmony', 'religious discourse', 'theological methodology', 'clerical guidance', 'jurisprudential principles', 'Shia Imami scholarship', 'legal interpretation', 'Islamic unity', 'scholarly disagreement', 'religious boundaries', 'pastoral responsibility', 'community welfare', 'Islamic governance', 'interfaith dialogue', 'intra-Muslim relations', 'modern Islamic law', 'religious identity', 'pluralistic society', 'traditional scholarship', 'contemporary challenges', 'divine guidance', 'spiritual harmony', 'teleological jurisprudence', 'prophetic tradition', 'Quranic foundation', 'hadith al-thaqalayn', 'infallible Imams', 'legal certainty', 'scholarly rigor', 'ethical boundaries', 'social harmony', 'Islamic values', 'community flourishing', 'divine proximity', 'justice and mercy', 'no harm principle', 'la darar wa la dirar', 'unified scholarship', 'religious leadership', 'pastoral care', 'Islamic civilization', 'modern governance', 'religious cohesion', 'scholarly integrity', 'community bonds', 'Islamic life', 'classical foundations', 'innovative methodology', 'legal precision', 'social needs', 'Muslim communities', 'jurisprudential innovation', 'scholarly evolution', 'religious tradition', 'Islamic ideals', 'collective life', 'individual guidance', 'human flourishing', 'religious scholarship', 'scholarly excellence', 'community preservation', 'Islamic legal literature', 'intellectual needs', 'social requirements', 'contemporary relevance', 'historical significance', 'methodological sophistication', 'practical applications', 'theoretical framework', 'preventive approach', 'proactive guidance', 'scholarly responsibility', 'community guardian', 'unified vision', 'religious commitment', 'scholarly dedication', 'pastoral concern', 'intellectual precision', 'divine will', 'prophetic example', 'classical methodology', 'modern adaptation', 'scholarly maturity', 'community service', 'legal guidance', 'spiritual leadership', 'academic excellence', 'practical wisdom', 'theoretical depth', 'methodological innovation', 'scholarly contribution', 'community impact', 'religious significance', 'intellectual achievement', 'pastoral effectiveness'],
    description = 'A comprehensive jurisprudential treatise by Grand Ayatollah Sayyid Muhammad al-Husayni al-Shirazi that develops a preventive methodology for maintaining Islamic unity while preserving scholarly rigor. The work combines classical usul al-fiqh principles with innovative dispute resolution techniques, establishing ethical boundaries for scholarly disagreement and hierarchical approaches to legal questions. Through systematic analysis of the relationship between certainty and doubt in Islamic law, al-Shirazi presents a framework that prioritizes community cohesion without compromising essential principles. The treatise serves as both a methodological guide for religious authorities and a pastoral response to contemporary challenges facing Muslim communities, demonstrating how traditional Islamic scholarship can evolve to meet modern needs while remaining grounded in classical foundations.'
WHERE id = '29083a94-4d92-4a6a-86ae-2a90f293ddda';

-- Verification query
SELECT id, title, title_alias, array_length(keywords, 1) as keywords_count, LEFT(description, 100) || '...' as description_preview
FROM books 
WHERE id = '29083a94-4d92-4a6a-86ae-2a90f293ddda';