-- SQL Update for: Muamrat Al-Ayat Al-Shaytaniyah
-- Generated: 2025-07-04
-- Processor: Fast-Mode-Islamic-Text-Processor-1

UPDATE books 
SET 
    title_alias = 'The Conspiracy of the Satanic Verses; Muamrat Al-Ayat Al-Shaytaniyah; Conspiracy of Satanic Verses; The Satanic Verses Conspiracy; Muamarat Ayat Shaytaniya; Orientalist Conspiracy; Satanic Verses Refutation; Anti-Orientalist Response; Islamic Apologetics; Quranic Defense; Prophetic Infallibility Defense; Western Academic Conspiracy; Islamic Response to Orientalism; Satanic Verses Debate; Quranic Integrity Defense',
    keywords = 'Satanic Verses; gharānīq incident; Orientalist conspiracy; Islamic apologetics; Quranic integrity; prophetic infallibility; ʿiṣma nabawīya; Orientalism; Western academia; Salman Rushdie; taḥrīf; textual corruption; Isrāʾīliyyāt; Israelite narratives; Islamic defense; Quranic authenticity; revelation; waḥy; hadith authentication; takhrīj; historical analysis; taḥlīl tārīkhī; religious authority; Islamic scholarship; traditional orthodoxy; Montgomery Watt; Maxime Rodinson; revisionist scholars; source criticism; naqd al-maṣādir; scholarly consensus; ijmāʿ; Islamic epistemology; revelation protection; satanic interference; mubahala; cursing verses; theological debate; religious polemics; Islamic-Christian dialogue; prophetic mission; risāla; Quranic exegesis; tafsīr; Tabari; Qurtubi; historical chronicles; tawārīkh; transmission chains; isnād; narrator reliability; jarḥ wa taʿdīl; textual variations; Islamic sources; Western methodology; colonial scholarship; academic bias; source selection; anachronistic interpretation; religious studies; comparative religion; Islamic studies; Middle Eastern studies; Quranic studies; hadith studies; Islamic history; prophetic biography; sīra; Islamic theology; kalām; Islamic philosophy; religious apologetics; interfaith dialogue; Islamic-Western relations; academic criticism; scholarly response; Islamic intellectual; religious authority; traditional Islam; orthodox Islam; Islamic orthodoxy; religious tradition; Islamic civilization; Muslim scholars; Islamic academia; religious scholarship; theological response; doctrinal defense; creedal protection; Islamic beliefs; Muslim faith; religious conviction; spiritual authority; divine revelation; prophetic protection; Islamic worldview; religious epistemology; faith and reason; tradition and modernity; Islam and West; academic freedom; scholarly debate; intellectual discourse; religious dialogue; interfaith understanding; Islamic representation; Muslim identity; religious minorities; academic institutions; Western universities; Islamic universities; religious education; theological training; Islamic curriculum; religious studies; comparative theology; interfaith studies; Middle Eastern studies; Oriental studies; Islamic civilization; Muslim culture; religious heritage; Islamic tradition; scholarly tradition; academic tradition; intellectual history; religious history; Islamic intellectual history; theological development; doctrinal evolution; religious thought; Islamic thought; Muslim scholarship; religious scholarship; theological scholarship; academic scholarship; scholarly methodology; research methods; source criticism; textual analysis; historical method; comparative method; interdisciplinary approach; religious studies methodology',
    description = 'A polemical Islamic treatise refuting the "Satanic Verses" narrative through systematic Quranic exegesis, hadith authentication, and historical analysis. The work challenges Western Orientalist scholarship that questions Quranic authenticity, defending traditional Islamic positions on prophetic infallibility and divine revelation protection. Drawing from classical Islamic sources including Tabari and Qurtubi, the author argues that the "Satanic Verses" narrative represents an Orientalist conspiracy to undermine Islamic credibility. The work examines transmission chains, narrator reliability, and textual variations to demonstrate the weakness of sources supporting the controversial narrative. Particularly relevant for contemporary Islamic apologetics addressing Western academic criticism and media representations of Islam. The systematic refutation approach reflects broader patterns in Islamic literature responding to Orientalist challenges while reinforcing internal Islamic confidence in scriptural authenticity and prophetic authority.'
WHERE id = '2da86738-d6ed-46b6-96f2-3c6a04ee1d66';