-- ======================================================================
-- BOOK 2: Nusus Al-Sharq Al-Adna Al-Qadimah
-- Author: Dr. Abdul Hamid Zaid
-- Processed: 2025-07-03
-- Status: PENDING
-- ======================================================================

UPDATE books SET
  title_alias = 'Ancient Near Eastern Texts; Nusus al-Sharq al-Adna al-Qadimah; Ancient Near East Texts; Nusus Sharq Adna Qadimah; Texts of the Ancient Near East; Ancient Middle Eastern Texts; Near Eastern Ancient Texts; Al-Sharq al-Adna al-Qadimah; Classical Near Eastern Literature; Ancient Oriental Texts',
  keywords = '{"Ancient Near East", "Near Eastern texts", "Nusus", "Sharq Adna", "Ancient texts", "Dr. Abdul Hamid Zaid", "Abdul Hamid Zaid", "Mesopotamian texts", "Egyptian texts", "Sumerian literature", "Akkadian literature", "Babylonian texts", "Ugaritic texts", "Canaanite texts", "Phoenician texts", "Cuneiform texts", "Hieroglyphic texts", "Ancient civilizations", "Pre-Islamic texts", "Comparative religion", "Historical linguistics", "Philology", "Translation studies", "Islamic studies", "Enuma Elish", "Epic of Gilgamesh", "Code of Hammurabi", "Book of the Dead", "Pyramid Texts", "Amarna Letters", "Baal Cycle", "Ancient wisdom literature", "Archaeological texts", "Historical records", "Religious texts", "Mythology", "Ancient languages", "Sumerian", "Akkadian", "Egyptian", "Hebrew", "Ugaritic", "Comparative literature", "Intertextuality", "Cultural studies", "Ancient history", "Middle Eastern studies", "Oriental studies", "Textual criticism", "Manuscript studies"}',
  description = 'In "Nusus Al-Sharq Al-Adna Al-Qadimah," Dr. Abdul Hamid Zaid analyzes ancient Near Eastern texts through comprehensive translation and comparative methodology. Zaid establishes that ancient Near Eastern texts provide essential historical and cultural context for understanding Islamic civilization, religious concepts, and literary traditions through systematic presentation of pre-Islamic civilizations and their literary heritage. This thesis is built upon exhaustive documentation from three foundations: philological analysis of ancient languages (Sumerian, Akkadian, Egyptian, Ugaritic), comparative linguistics demonstrating cultural continuities, and historical-critical translation methodology that preserves textual integrity while making sources accessible to Arabic-speaking scholars. The work grounds its argument in critical examination of major texts including the Epic of Gilgamesh, Code of Hammurabi, Egyptian Book of the Dead, and Ugaritic Ba''al Cycle, while systematically addressing intertextual relationships with Quranic narratives and Islamic historical accounts. Zaid''s comprehensive approach transforms disparate ancient sources into a unified scholarly tool, offering Arabic-speaking researchers an indispensable resource for understanding the historical and cultural foundations underlying Islamic civilization and its relationship to earlier Middle Eastern traditions.'
WHERE id = '6ddc7a2d-4902-4ff6-a261-6790d75994cd';