-- Book Enrichment SQL for Tarikh Ahl al-Bayt
-- Generated: 2025-07-04
-- Book ID: 6a824afe-24ec-47b2-ad21-5dcbfadd72b1

UPDATE books SET
    title_alias = 'Tarikh Ahl al-Bayt; Tarikh Ahl al Bayt; Tarikh Ahlul Bayt; History of the Prophet''s Family; History of Ahl al-Bayt; The History of the Blessed Family; Chronicle of the Prophet''s Household; Tarikh Ahl-e-Bayt; History of the Fourteen Infallibles; The Sacred Household History; Prophet''s Family Chronicles; Ahl al-Bayt Historical Account; The Blessed Lineage History; Family of the Prophet History; Household of Muhammad History',
    keywords = ARRAY[
        'Ahl al-Bayt', 'Ahlul Bayt', 'Prophet''s family', 'Household of Muhammad', 'Fourteen infallibles', 'Ma''sumin', 'Prophet Muhammad', 'Imam Ali', 'Fatima al-Zahra', 'Imam Hasan', 'Imam Husayn', 'Twelve Imams', 'Sayyida Fatima', 'Ali ibn Abi Talib', 'Hasan ibn Ali', 'Husayn ibn Ali', 'Zayn al-Abidin', 'Muhammad al-Baqir', 'Ja''far al-Sadiq', 'Musa al-Kadhim', 'Ali al-Rida', 'Muhammad al-Jawad', 'Ali al-Hadi', 'Hasan al-Askari', 'Mahdi', 'Imam al-Mahdi', 'Occultation', 'Ghaybah', 'Wilayah', 'Guardianship', 'Succession', 'Caliphate', 'Imamate', 'Infallibility', 'Ismah', 'Shi''a Islam', 'Islamic history', 'Prophetic tradition', 'Hadith al-Kisa', 'Hadith al-Thaqalayn', 'Verse of Purification', 'Ayat al-Tathir', 'Mubahala', 'Ghadir Khumm', 'Karbala', 'Ashura', 'Martyrdom', 'Sayyids', 'Blessed lineage', 'Divine guidance', 'Spiritual leadership', 'Islamic civilization', 'Prophetic household', 'Sacred family', 'Religious authority', 'Theological significance', 'Genealogy', 'Nasab', 'Banu Hashim', 'Early Islamic history', 'Companions', 'Sahaba', 'Followers', 'Shi''a', 'Sunni', 'Islamic unity', 'Veneration', 'Respect', 'Love', 'Mawadda', 'Intercession', 'Shafa''ah', 'End times', 'Eschatology', 'Justice', 'Adl', 'Righteousness', 'Piety', 'Taqwa', 'Islamic teachings', 'Quranic exegesis', 'Tafsir', 'Hadith studies', 'Islamic jurisprudence', 'Fiqh', 'Islamic theology', 'Kalam', 'Mysticism', 'Sufism', 'Spiritual guidance', 'Moral exemplars', 'Role models', 'Islamic ethics', 'Character', 'Akhlaq', 'Prayer', 'Salah', 'Supplication', 'Du''a', 'Worship', 'Ibadah', 'Islamic culture', 'Muslim identity', 'Religious devotion', 'Pious predecessors', 'Salaf', 'Islamic scholarship', 'Ulama', 'Religious education', 'Tarbiyah', 'Spiritual development', 'Self-purification', 'Tazkiyah'
    ],
    description = 'A comprehensive historical chronicle documenting the lives, teachings, and significance of the Prophet Muhammad''s household (Ahl al-Bayt) throughout Islamic history. This work focuses on the blessed family lineage, particularly the fourteen infallibles (Ma''sumin) revered in Shi''a tradition, while acknowledging the broader veneration of the Prophet''s family across all Islamic communities.

The chronicle integrates Quranic exegesis, authentic hadith literature, and historical narratives to present a systematic account of each family member''s life and contributions. Beginning with Prophet Muhammad as the head of the household and Sayyida Fatima al-Zahra as the "leader of the women of Paradise," the work traces the spiritual and temporal significance of the blessed lineage through Imam Ali ibn Abi Talib, his sons Hasan and Husayn, and the chain of nine Imams culminating with the awaited Mahdi.

The work emphasizes the Quranic foundation of the household''s special status, particularly the Verse of Purification (Ayat al-Tathir) and related prophetic traditions like Hadith al-Kisa and Hadith al-Thaqalayn. It documents pivotal events including the Mubahala, Ghadir Khumm, the tragedy of Karbala, and the doctrine of occultation (ghaybah).

Beyond biographical documentation, the chronicle explores the theological concept of Wilayah (guardianship), the doctrine of infallibility (ismah), and the continuous spiritual guidance provided by the Prophet''s family. It demonstrates how the household members served as exemplars of Islamic values, contributors to Islamic scholarship, and sources of divine guidance during various historical periods.

The work serves multiple audiences: providing Shi''a Muslims with comprehensive documentation of their spiritual guides, offering other Muslims insight into the venerated status of the Prophet''s family, and contributing to Islamic historical and theological scholarship. The integration of genealogical precision with spiritual significance makes it an essential reference for understanding Islamic leadership, divine guidance, and the continuing relevance of the blessed family in contemporary Islamic thought and practice.'
WHERE id = '6a824afe-24ec-47b2-ad21-5dcbfadd72b1';